try{
    console.log(a);
    
}
catch(err){
    console.log("err");
    
}
console.log(456);
